# Generated by Django 5.2.3 on 2025-07-04 04:09

import cloudinary.models
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('account', '0003_customuser_friends_chatroom_friendrequest'),
    ]

    operations = [
        migrations.AlterField(
            model_name='customuser',
            name='profile_image',
            field=cloudinary.models.CloudinaryField(default=True, max_length=255, verbose_name='image'),
            preserve_default=False,
        ),
    ]
